import 'dart:io';

import 'package:image/image.dart';
import 'package:path/path.dart' as p;

enum IconCanvasShape {
  transparent,
  square,
  roundedSquare,
  circle,
}

class IconComposerFlavorConfig {
  const IconComposerFlavorConfig({
    required this.name,
    required this.suffix,
    required this.label,
    required this.labelColor,
    required this.labelBackgroundColor,
  });

  final String name;
  final String suffix;
  final String? label;
  final String labelColor;
  final String? labelBackgroundColor;
}

class IconComposerPresetConfig {
  const IconComposerPresetConfig({
    required this.size,
    required this.shape,
    required this.logoWidthRatio,
    required this.logoCenterYRatio,
    required this.cornerRadiusRatio,
    required this.labelHeightRatio,
    required this.labelBottomMarginRatio,
  });

  final int size;
  final IconCanvasShape shape;
  final double logoWidthRatio;
  final double logoCenterYRatio;
  final double cornerRadiusRatio;
  final double labelHeightRatio;
  final double labelBottomMarginRatio;
}

class IconComposerConfig {
  const IconComposerConfig({
    required this.enabled,
    required this.logoSvgPath,
    required this.outputPath,
    required this.backgroundColor,
    required this.logoRenderSize,
    required this.flavors,
    required this.normal,
    required this.round,
    required this.playStore,
    required this.transparent,
  });

  final bool enabled;
  final String logoSvgPath;
  final String outputPath;
  final String backgroundColor;
  final int logoRenderSize;
  final List<IconComposerFlavorConfig> flavors;
  final IconComposerPresetConfig normal;
  final IconComposerPresetConfig round;
  final IconComposerPresetConfig playStore;
  final IconComposerPresetConfig transparent;
}

class IconComposer {
  const IconComposer({
    required this.config,
  });

  final IconComposerConfig config;

  Future<void> generate() async {
    if (!config.enabled) {
      return;
    }

    final logo = await _renderSvgToImage();

    for (final flavor in config.flavors) {
      final flavorPath = p.join(config.outputPath, flavor.name);

      await _writeIcon(
        logo: logo,
        flavor: flavor,
        preset: config.normal,
        outputPath: p.join(
          flavorPath,
          'wareed_launcher_icon${flavor.suffix}.png',
        ),
      );

      await _writeIcon(
        logo: logo,
        flavor: flavor,
        preset: config.round,
        outputPath: p.join(
          flavorPath,
          'wareed_launcher_round_icon${flavor.suffix}.png',
        ),
      );

      await _writeIcon(
        logo: logo,
        flavor: flavor,
        preset: config.playStore,
        outputPath: p.join(
          flavorPath,
          'wareed_launcher_playstore${flavor.suffix}.png',
        ),
      );
    }

    await _writeIcon(
      logo: logo,
      flavor: const IconComposerFlavorConfig(
        name: 'shared',
        suffix: '',
        label: null,
        labelColor: '#FFFFFF',
        labelBackgroundColor: null,
      ),
      preset: config.transparent,
      outputPath: p.join(
        config.outputPath,
        'wareed_logo_transparent.png',
      ),
    );
  }

  Future<Image> _renderSvgToImage() async {
    final source = File(config.logoSvgPath);

    if (!source.existsSync()) {
      throw FileSystemException('SVG logo not found', source.path);
    }

    final tempDirectory = await Directory.systemTemp.createTemp(
      'very_good_launcher_icons_',
    );

    try {
      final outputPath = p.join(tempDirectory.path, 'logo.png');

      final result = await Process.run(
        'resvg',
        [
          '--width',
          config.logoRenderSize.toString(),
          '--height',
          config.logoRenderSize.toString(),
          source.path,
          outputPath,
        ],
      );

      if (result.exitCode != 0) {
        throw ProcessException(
          'resvg',
          [
            '--width',
            config.logoRenderSize.toString(),
            '--height',
            config.logoRenderSize.toString(),
            source.path,
            outputPath,
          ],
          '${result.stderr}',
          result.exitCode,
        );
      }

      final outputFile = File(outputPath);

      if (!outputFile.existsSync()) {
        throw FileSystemException('resvg output not found', outputPath);
      }

      final image = decodePng(outputFile.readAsBytesSync());

      if (image == null) {
        throw FormatException('Invalid PNG generated by resvg: $outputPath');
      }

      return image;
    } finally {
      if (tempDirectory.existsSync()) {
        await tempDirectory.delete(recursive: true);
      }
    }
  }

  Future<void> _writeIcon({
    required Image logo,
    required IconComposerFlavorConfig flavor,
    required IconComposerPresetConfig preset,
    required String outputPath,
  }) async {
    final canvas = Image(
      width: preset.size,
      height: preset.size,
      numChannels: 4,
    );

    fill(canvas, color: ColorRgba8(0, 0, 0, 0));

    if (preset.shape != IconCanvasShape.transparent) {
      _drawBackground(
        canvas: canvas,
        shape: preset.shape,
        backgroundColor: _hexToColor(config.backgroundColor),
        cornerRadius: (preset.size * preset.cornerRadiusRatio).round(),
      );
    }

    final logoWidth = (preset.size * preset.logoWidthRatio).round();
    final resizedLogo = copyResize(
      logo,
      width: logoWidth,
      interpolation: Interpolation.cubic,
    );

    final logoX = ((preset.size - resizedLogo.width) / 2).round();
    final logoY =
        ((preset.size * preset.logoCenterYRatio) - (resizedLogo.height / 2))
            .round();

    compositeImage(
      canvas,
      resizedLogo,
      dstX: logoX,
      dstY: logoY,
    );

    final label = flavor.label;

    if (label != null && label.trim().isNotEmpty) {
      _drawLabel(
        canvas: canvas,
        label: label,
        labelColor: _hexToColor(flavor.labelColor),
        backgroundColor: _hexToColor(
          flavor.labelBackgroundColor ?? '#000000',
        ),
        height: (preset.size * preset.labelHeightRatio).round(),
        bottomMargin: (preset.size * preset.labelBottomMarginRatio).round(),
      );
    }

    final output = File(outputPath);
    await output.parent.create(recursive: true);
    await output.writeAsBytes(encodePng(canvas));

    stdout.writeln('Composed ${p.normalize(output.path)}');
  }

  void _drawBackground({
    required Image canvas,
    required IconCanvasShape shape,
    required Color backgroundColor,
    required int cornerRadius,
  }) {
    switch (shape) {
      case IconCanvasShape.transparent:
        return;

      case IconCanvasShape.square:
        fill(canvas, color: backgroundColor);

      case IconCanvasShape.circle:
        fillCircle(
          canvas,
          x: canvas.width ~/ 2,
          y: canvas.height ~/ 2,
          radius: canvas.width ~/ 2,
          color: backgroundColor,
        );

      case IconCanvasShape.roundedSquare:
        _fillRoundedRect(
          canvas: canvas,
          x: 0,
          y: 0,
          width: canvas.width,
          height: canvas.height,
          radius: cornerRadius,
          color: backgroundColor,
        );
    }
  }

  void _drawLabel({
    required Image canvas,
    required String label,
    required Color labelColor,
    required Color backgroundColor,
    required int height,
    required int bottomMargin,
  }) {
    if (height <= 0) {
      return;
    }

    final labelWidth = (canvas.width * 0.50).round();
    final labelX = ((canvas.width - labelWidth) / 2).round();
    final labelY = canvas.height - bottomMargin - height;
    final radius = (height * 0.22).round();

    _fillRoundedRect(
      canvas: canvas,
      x: labelX,
      y: labelY,
      width: labelWidth,
      height: height,
      radius: radius,
      color: backgroundColor,
    );

    final font = arial48;
    final textWidth = _estimateTextWidth(label);
    final textX = labelX + ((labelWidth - textWidth) / 2).round();
    final textY = labelY + ((height - 48) / 2).round();

    drawString(
      canvas,
      label,
      font: font,
      x: textX,
      y: textY,
      color: labelColor,
    );
  }

  int _estimateTextWidth(String text) {
    return text.length * 30;
  }

  void _fillRoundedRect({
    required Image canvas,
    required int x,
    required int y,
    required int width,
    required int height,
    required int radius,
    required Color color,
  }) {
    if (radius <= 0) {
      fillRect(
        canvas,
        x1: x,
        y1: y,
        x2: x + width,
        y2: y + height,
        color: color,
      );
      return;
    }

    final clampedRadius = radius.clamp(0, width ~/ 2).clamp(0, height ~/ 2);

    fillRect(
      canvas,
      x1: x + clampedRadius,
      y1: y,
      x2: x + width - clampedRadius,
      y2: y + height,
      color: color,
    );

    fillRect(
      canvas,
      x1: x,
      y1: y + clampedRadius,
      x2: x + width,
      y2: y + height - clampedRadius,
      color: color,
    );

    fillCircle(
      canvas,
      x: x + clampedRadius,
      y: y + clampedRadius,
      radius: clampedRadius,
      color: color,
    );

    fillCircle(
      canvas,
      x: x + width - clampedRadius,
      y: y + clampedRadius,
      radius: clampedRadius,
      color: color,
    );

    fillCircle(
      canvas,
      x: x + clampedRadius,
      y: y + height - clampedRadius,
      radius: clampedRadius,
      color: color,
    );

    fillCircle(
      canvas,
      x: x + width - clampedRadius,
      y: y + height - clampedRadius,
      radius: clampedRadius,
      color: color,
    );
  }

  Color _hexToColor(String hex) {
    final normalized = hex.replaceAll('#', '');

    if (normalized.length != 6) {
      throw FormatException('Invalid hex color: $hex');
    }

    final value = int.parse(normalized, radix: 16);

    return ColorUint8.rgb(
      (value >> 16) & 0xFF,
      (value >> 8) & 0xFF,
      value & 0xFF,
    );
  }
}
